---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: test-projectname
spec:
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
    scaleUp:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-projectname
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90