---
apiVersion: v1
kind: Service
metadata:
  name: test-projectname
  labels:
    app: test-projectname
spec:
  selector:
    app: test-projectname
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP

